config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: "registration"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :departments
  resources :users
  resources :roles
  resources :permissions
  resources :cars
  namespace :registers do
    resources :car_inspections, except: :show
  end

  resources :partners do
    collection { post :import }
  end
  resources :product_types
  resources :order_logs
  # Defines the root path route ("/")
  root "departments#index"
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
    load_and_authorize_resource

    def index
      @product_types = ProductType.all #.order(:name).page(params[:page])

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @product_types }
      end
    end

    def show
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @product_type }
      end
    end

    def new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @product_type }
      end
    end

    def edit
    end

    def create
      @product_type = ProductType.new(product_type_params)

      respond_to do |format|
        if @product_type.save
          format.html { redirect_to @product_type, notice: 'Permission was successfully created.' }
          format.json { render json: @product_type, status: :created, location: @product_type }
        else
          format.html { render action: "new" }
          format.json { render json: @product_type.errors, status: :unprocessable_entity }
        end
      end
    end

    def update

      respond_to do |format|
        if @product_type.update(product_type_params)
          format.html { redirect_to @product_type, notice: 'Permission was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @product_type.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @product_type.destroy
      respond_to do |format|
        format.html { redirect_to product_types_url }
        format.json { head :no_content }
      end
    end

    protected

    def product_type_params
      permitted_fields = [
        :name
      ]

      params.require(:product_type).permit(permitted_fields)
    end
  end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= custom_form_for(@product_type, bootstrap3_form_options(html_class: "agent-form")) do |f| %>
      <div class="bs-component">
        <div class="tab-pane" id="cars">
          <div class="row">
            <% if @product_type.errors.present? %>
              <div class="alert alert-danger">
                <% @product_type.errors.full_messages.each do |msg| %>
                  <p><%= msg %></p>
                <% end %>
              </div>
            <% end %>

            <%# if can? :set_active, @agent %>
            <%#= f.input :is_active %>
            <%# end %>

            <%# if can?(:view_agent_tier, @agent) %>
            <%#= f.association :roles, collection: Role.all, include_blank: false, multiple: false %>
            <%# end %>


            <%= f.input :name %>
          </div>
          <div class="row">
            <div class="col-sm-offset-3 col-sm-2 p-3">
              <%= f.button :submit, "Save", class: "btn-primary btn-block" %>
              <%= link_to("Cancel", product_types_path, class: "btn btn-dark btn-block") %>
            </div>
          </div>
        </div>

      </div>

    <% end %>
  </div>
</div>

app/views/product_types/index.html.erb
<h1><%= I18n.t("product_types") %></h1>

<%= link_to 'New product type', new_product_type_path %>
<div>
  <div>
    <table class="table  table-striped">
      <thead>
      <tr>
        <th scope="col"><%= I18n.t("activerecord.attributes.product_type.name") %></th>
<!--        <th scope="col"><%#= I18n.t("activerecord.attributes.partner.email") %></th>-->
<!--        <th scope="col"><%#= I18n.t("activerecord.attributes.partner.address") %></th>-->
<!--        <th scope="col"><%#= I18n.t("activerecord.attributes.partner.phone_number") %></th>-->
      </tr>
      </thead>
      <tbody>
      <% if @product_types %>
        <% @product_types.each do |product_type| %>
          <tr>
            <td>
              <a href="<%= partner_path(product_type) %>">
                <h5> <%= product_type.name %> </h5>
              </a>
            </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/product_types/new.html.erb
<h1><%= I18n.t("activerecord.attributes.product_type.new_product_type")%></h1>
<%= render partial: "form" %>

app/views/product_types/show.html.erb
<div>
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
<!--        <img src="..." class="img-fluid rounded-start" alt="...">-->
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= @product_type.name %></h5>
          <div class="mb15">
            <%= link_to("Edit", edit_product_type_path(@product_type), class: "btn btn-primary btn-block pv10 fw600 mb10") if can?(:update, @product_type)  %>
            <%= link_to("Destroy", product_type_path(@product_type), data: { turbo_method: :delete, turbo_confirm: "Удалить партнера?" }, class: "btn btn-danger btn-block") if can?(:destroy, @product_type) %>
            <%= link_to("All Product Type", product_types_path, class: "btn btn-block btn-dark pv10 fw600 mb10")%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>