config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: "registration"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :departments
  resources :users
  resources :roles
  resources :permissions
  resources :cars
  namespace :registers do
    resources :car_inspections, except: :show
  end

  resources :partners do
    collection { post :import }
  end
  resources :product_types
  resources :order_logs
  # Defines the root path route ("/")
  root "departments#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  # enum roles: [:user, :moderator, :admin]
  # after_initialize :set_default_role, :if => :new_record?

  has_one_attached :avatar

  has_and_belongs_to_many :departments
  has_and_belongs_to_many :roles

  validate :one_department_is_selected

  def full_name
    "#{self.last_name} #{self.first_name} #{self.patronymic}"
  end

  def set_default_role
    self.role ||= :user
  end

  def self.gender_attributes_for_select
    roles.map do |role, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.roles.#{role}"), role]
    end
  end

  private

  def one_department_is_selected
    unless (self.departments.size > 0)
      errors.add(:departments, "You must select a department")
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(resource_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end


  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(resource_params)
        format.html { redirect_to @user, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  def resource_params
    permited_fields = [:email, {role_ids: []}, :avatar, :bday, :first_name, :last_name, :patronymic, :password, :password_confirmation, {department_ids: []}  ]
    params.require(:user).permit(permited_fields)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= custom_form_for(@user, bootstrap3_form_options(html_class: "agent-form")) do |f| %>
      <div class="bs-component">
        <div class="tab-pane" id="users">
          <div class="row">
            <% if @user.errors.present? %>
              <div class="alert alert-danger">
                <% @user.errors.full_messages.each do |msg| %>
                  <p><%= msg %></p>
                <% end %>
              </div>
            <% end %>

            <%# if can? :set_active, @agent %>
            <%#= f.input :is_active %>
            <%# end %>

            <%# if can?(:view_agent_tier, @agent) %>
            <%= f.association :roles, collection: Role.all, include_blank: false, multiple: false %>
            <%# end %>
            <%= f.input :first_name %>
            <%= f.input :last_name %>
            <%= f.input :patronymic %>
            <%= f.input :email %>
            <%= f.association :departments, collection: Department.all, class: "selectpicker", data_live_search: "true" %>
            <% if f.object.new_record? %>
            <div class="field">
              <%= f.label :password %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "new-password" %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
            </div>
            <% end %><br />
            <div class='field p-3'>
              <%= f.label :bday %>
              <%= f.date_select :bday, start_year: 1950 %>
            </div>
            <%= f.input :avatar %>
          </div>
          <div class="row">
            <div class="col-sm-offset-3 col-sm-2 p-3">
              <%= f.button :submit, "Save", class: "btn-primary btn-block" %>
              <%= link_to("Cancel", users_path, class: "btn btn-dark btn-block") %>
            </div>
          </div>
        </div>

      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
  <h1><%= I18n.t("users")%></h1>
  <%= link_to 'New User', new_user_path %>
  <div>
    <div>
      <table class="table  table-striped">
        <thead>
        <tr>
          <th scope="col">Image</th>
          <th scope="col">Full Name</th>
          <th scope="col">Email</th>
          <th scope="col">Role</th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.avatar, class: " rounded-circle", style: "width: 40px; height: 40px;" if user.avatar.attached? %></td>
            <td><%= user.full_name %></td>
            <td><a href="<%= user_path(user) %>">
              <h5> <%= user.email %></h5>
            </a></td>
            <td><% user.roles.each do |role| %>
                <p><%= link_to(role.title, role_path(role), class: "col-sm-4") %></p>
                <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/users/show.html.erb
<div>
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
<!--        <img src="..." class="img-fluid rounded-start" alt="...">-->
        <%= image_tag @user.avatar, class: "img-fluid rounded-start" if @user.avatar.attached? %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= @user.full_name %></h5>
          <% @user.departments.each do |department| %>
            <p><%= link_to(department.title, department_path(department), class: "col-sm-4") %></p>
          <% end %>
          <p class="card-text"><%= @user.email %></p>
<!--          <p class="card-text"><%#= I18n.t("activerecord.attributes.user.roles.#{@user.roles}") %></p>-->
          <% @user.roles.each do |role| %>
            <p><%= link_to(role.title, role_path(role), class: "col-sm-4") %></p>
          <% end %>
          <p class="card-text"><small class="text-muted"><%= @user.bday %></small></p>
          <div class="mb15">
            <%= link_to("Edit", edit_user_path(@user), class: "btn btn-primary btn-block pv10 fw600 mb10") if can?(:update, User)  %>
            <%= link_to("Destroy", user_path(@user), data: {turbo_method: :delete, confirm: "Are you sure?"}, class: "btn btn-danger btn-block") if can?(:destroy, User) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>