config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: "registration"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :departments
  resources :users
  resources :roles
  resources :permissions
  resources :cars
  namespace :registers do
    resources :car_inspections, except: :show
  end

  resources :partners do
    collection { post :import }
  end
  resources :product_types
  resources :order_logs
  # Defines the root path route ("/")
  root "departments#index"
end

app/views/shared/_all_block.html.erb
<!--        <!-- Sale & Revenue Start -->
<!--        <div class="container-fluid pt-4 px-4">-->
<!--          <div class="row g-4">-->
<!--            <div class="col-sm-6 col-xl-3">-->
<!--              <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">-->
<!--                <i class="fa fa-chart-line fa-3x text-primary"></i>-->
<!--                <div class="ms-3">-->
<!--                  <p class="mb-2">Today Sale</p>-->
<!--                  <h6 class="mb-0">$1234</h6>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="col-sm-6 col-xl-3">-->
<!--              <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">-->
<!--                <i class="fa fa-chart-bar fa-3x text-primary"></i>-->
<!--                <div class="ms-3">-->
<!--                  <p class="mb-2">Total Sale</p>-->
<!--                  <h6 class="mb-0">$1234</h6>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="col-sm-6 col-xl-3">-->
<!--              <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">-->
<!--                <i class="fa fa-chart-area fa-3x text-primary"></i>-->
<!--                <div class="ms-3">-->
<!--                  <p class="mb-2">Today Revenue</p>-->
<!--                  <h6 class="mb-0">$1234</h6>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="col-sm-6 col-xl-3">-->
<!--              <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">-->
<!--                <i class="fa fa-chart-pie fa-3x text-primary"></i>-->
<!--                <div class="ms-3">-->
<!--                  <p class="mb-2">Total Revenue</p>-->
<!--                  <h6 class="mb-0">$1234</h6>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--        <!-- Sale & Revenue End -->


<!--        <!-- Sales Chart Start -->
<!--        <div class="container-fluid pt-4 px-4">-->
<!--          <div class="row g-4">-->
<!--            <div class="col-sm-12 col-xl-6">-->
<!--              <div class="bg-light text-center rounded p-4">-->
<!--                <div class="d-flex align-items-center justify-content-between mb-4">-->
<!--                  <h6 class="mb-0">Worldwide Sales</h6>-->
<!--                  <a href="">Show All</a>-->
<!--                </div>-->
<!--                <canvas id="worldwide-sales"></canvas>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="col-sm-12 col-xl-6">-->
<!--              <div class="bg-light text-center rounded p-4">-->
<!--                <div class="d-flex align-items-center justify-content-between mb-4">-->
<!--                  <h6 class="mb-0">Salse & Revenue</h6>-->
<!--                  <a href="">Show All</a>-->
<!--                </div>-->
<!--                <canvas id="salse-revenue"></canvas>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--        <!-- Sales Chart End -->


<!--        <!-- Recent Sales Start -->
<!--        <div class="container-fluid pt-4 px-4">-->
<!--          <div class="bg-light text-center rounded p-4">-->
<!--            <div class="d-flex align-items-center justify-content-between mb-4">-->
<!--              <h6 class="mb-0">Recent Salse</h6>-->
<!--              <a href="">Show All</a>-->
<!--            </div>-->
<!--            <div class="table-responsive">-->
<!--              <table class="table text-start align-middle table-bordered table-hover mb-0">-->
<!--                <thead>-->
<!--                <tr class="text-dark">-->
<!--                  <th scope="col"><input class="form-check-input" type="checkbox"></th>-->
<!--                  <th scope="col">Date</th>-->
<!--                  <th scope="col">Invoice</th>-->
<!--                  <th scope="col">Customer</th>-->
<!--                  <th scope="col">Amount</th>-->
<!--                  <th scope="col">Status</th>-->
<!--                  <th scope="col">Action</th>-->
<!--                </tr>-->
<!--                </thead>-->
<!--                <tbody>-->
<!--                <tr>-->
<!--                  <td><input class="form-check-input" type="checkbox"></td>-->
<!--                  <td>01 Jan 2045</td>-->
<!--                  <td>INV-0123</td>-->
<!--                  <td>Jhon Doe</td>-->
<!--                  <td>$123</td>-->
<!--                  <td>Paid</td>-->
<!--                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                  <td><input class="form-check-input" type="checkbox"></td>-->
<!--                  <td>01 Jan 2045</td>-->
<!--                  <td>INV-0123</td>-->
<!--                  <td>Jhon Doe</td>-->
<!--                  <td>$123</td>-->
<!--                  <td>Paid</td>-->
<!--                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                  <td><input class="form-check-input" type="checkbox"></td>-->
<!--                  <td>01 Jan 2045</td>-->
<!--                  <td>INV-0123</td>-->
<!--                  <td>Jhon Doe</td>-->
<!--                  <td>$123</td>-->
<!--                  <td>Paid</td>-->
<!--                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                  <td><input class="form-check-input" type="checkbox"></td>-->
<!--                  <td>01 Jan 2045</td>-->
<!--                  <td>INV-0123</td>-->
<!--                  <td>Jhon Doe</td>-->
<!--                  <td>$123</td>-->
<!--                  <td>Paid</td>-->
<!--                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                  <td><input class="form-check-input" type="checkbox"></td>-->
<!--                  <td>01 Jan 2045</td>-->
<!--                  <td>INV-0123</td>-->
<!--                  <td>Jhon Doe</td>-->
<!--                  <td>$123</td>-->
<!--                  <td>Paid</td>-->
<!--                  <td><a class="btn btn-sm btn-primary" href="">Detail</a></td>-->
<!--                </tr>-->
<!--                </tbody>-->
<!--              </table>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--        <!-- Recent Sales End -->


<!--        <!-- Widgets Start -->
<!--        <div class="container-fluid pt-4 px-4">-->
<!--          <div class="row g-4">-->
<!--            <div class="col-sm-12 col-md-6 col-xl-4">-->
<!--              <div class="h-100 bg-light rounded p-4">-->
<!--                <div class="d-flex align-items-center justify-content-between mb-2">-->
<!--                  <h6 class="mb-0">Messages</h6>-->
<!--                  <a href="">Show All</a>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center border-bottom py-3">-->
<%#= image_tag "user.jpg", class: "rounded-circle", style: "width: 40px; height: 40px;"  %>

<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 justify-content-between">-->
<!--                      <h6 class="mb-0">Jhon Doe</h6>-->
<!--                      <small>15 minutes ago</small>-->
<!--                    </div>-->
<!--                    <span>Short message goes here...</span>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center border-bottom py-3">-->
<%#= image_tag "user.jpg", class: "rounded-circle", style: "width: 40px; height: 40px;"  %>

<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 justify-content-between">-->
<!--                      <h6 class="mb-0">Jhon Doe</h6>-->
<!--                      <small>15 minutes ago</small>-->
<!--                    </div>-->
<!--                    <span>Short message goes here...</span>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center border-bottom py-3">-->
<%#= image_tag "user.jpg", class: "rounded-circle", style: "width: 40px; height: 40px;"  %>

<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 justify-content-between">-->
<!--                      <h6 class="mb-0">Jhon Doe</h6>-->
<!--                      <small>15 minutes ago</small>-->
<!--                    </div>-->
<!--                    <span>Short message goes here...</span>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center pt-3">-->
<%#= image_tag "user.jpg", class: "rounded-circle", style: "width: 40px; height: 40px;"  %>

<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 justify-content-between">-->
<!--                      <h6 class="mb-0">Jhon Doe</h6>-->
<!--                      <small>15 minutes ago</small>-->
<!--                    </div>-->
<!--                    <span>Short message goes here...</span>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="col-sm-12 col-md-6 col-xl-4">-->
<!--              <div class="h-100 bg-light rounded p-4">-->
<!--                <div class="d-flex align-items-center justify-content-between mb-4">-->
<!--                  <h6 class="mb-0">Calender</h6>-->
<!--                  <a href="">Show All</a>-->
<!--                </div>-->
<!--                <div id="calender"></div>-->
<!--              </div>-->
<!--            </div>-->
<!--            <div class="col-sm-12 col-md-6 col-xl-4">-->
<!--              <div class="h-100 bg-light rounded p-4">-->
<!--                <div class="d-flex align-items-center justify-content-between mb-4">-->
<!--                  <h6 class="mb-0">To Do List</h6>-->
<!--                  <a href="">Show All</a>-->
<!--                </div>-->
<!--                <div class="d-flex mb-2">-->
<!--                  <input class="form-control bg-transparent" type="text" placeholder="Enter task">-->
<!--                  <button type="button" class="btn btn-primary ms-2">Add</button>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center border-bottom py-2">-->
<!--                  <input class="form-check-input m-0" type="checkbox">-->
<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 align-items-center justify-content-between">-->
<!--                      <span>Short task goes here...</span>-->
<!--                      <button class="btn btn-sm"><i class="fa fa-times"></i></button>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center border-bottom py-2">-->
<!--                  <input class="form-check-input m-0" type="checkbox">-->
<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 align-items-center justify-content-between">-->
<!--                      <span>Short task goes here...</span>-->
<!--                      <button class="btn btn-sm"><i class="fa fa-times"></i></button>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center border-bottom py-2">-->
<!--                  <input class="form-check-input m-0" type="checkbox" checked>-->
<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 align-items-center justify-content-between">-->
<!--                      <span><del>Short task goes here...</del></span>-->
<!--                      <button class="btn btn-sm text-primary"><i class="fa fa-times"></i></button>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center border-bottom py-2">-->
<!--                  <input class="form-check-input m-0" type="checkbox">-->
<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 align-items-center justify-content-between">-->
<!--                      <span>Short task goes here...</span>-->
<!--                      <button class="btn btn-sm"><i class="fa fa-times"></i></button>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--                <div class="d-flex align-items-center pt-2">-->
<!--                  <input class="form-check-input m-0" type="checkbox">-->
<!--                  <div class="w-100 ms-3">-->
<!--                    <div class="d-flex w-100 align-items-center justify-content-between">-->
<!--                      <span>Short task goes here...</span>-->
<!--                      <button class="btn btn-sm"><i class="fa fa-times"></i></button>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--        <!-- Widgets End -->




<!--      <!-- Back to Top -->
<!--      <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>-->
<!--    </div>-->
<%#= yield %>

app/views/shared/_footer.html.erb
<!-- Footer Start -->
<div class="container-fluid pt-4 px-4">
  <div class="bg-light rounded-top p-4">
    <div class="row">
      <div class="col-12 col-sm-6 text-center text-sm-start">
        &copy; <a href="#">Your Site Name</a>, All Right Reserved.
      </div>
      <div class="col-12 col-sm-6 text-center text-sm-end">
        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
        Designed By <a href="https://htmlcodex.com">HTML Codex</a>
        </br>
        Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
      </div>
    </div>
  </div>
</div>
<!-- Footer End -->

app/views/shared/_header.html.erb
<!-- Navbar Start -->
<nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
  <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
  </a>
  <a href="#" class="sidebar-toggler flex-shrink-0">
    <i class="fa fa-bars"></i>
  </a>
  <form class="d-none d-md-flex ms-4">
    <input class="form-control border-0" type="search" placeholder="Search">
  </form>
  <div class="navbar-nav align-items-center ms-auto">
    <div class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
        <i class="fa fa-envelope me-lg-2"></i>
        <span class="d-none d-lg-inline-flex">Message</span>
      </a>
      <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
        <a href="#" class="dropdown-item">
          <div class="d-flex align-items-center">
            <%= image_tag "user.jpg", class: "rounded-circle", style: "width: 40px; height: 40px;"  %>
            <div class="ms-2">
              <h6 class="fw-normal mb-0">Jhon send you a message</h6>
              <small>15 minutes ago</small>
            </div>
          </div>
        </a>
        <hr class="dropdown-divider">
        <a href="#" class="dropdown-item">
          <div class="d-flex align-items-center">
            <%= image_tag "user.jpg", class: "rounded-circle", style: "width: 40px; height: 40px;"  %>
            <div class="ms-2">
              <h6 class="fw-normal mb-0">Jhon send you a message</h6>
              <small>15 minutes ago</small>
            </div>
          </div>
        </a>
        <hr class="dropdown-divider">
        <a href="#" class="dropdown-item">
          <div class="d-flex align-items-center">
            <%= image_tag "user.jpg", class: "rounded-circle", style: "width: 40px; height: 40px;"  %>
            <div class="ms-2">
              <h6 class="fw-normal mb-0">Jhon send you a message</h6>
              <small>15 minutes ago</small>
            </div>
          </div>
        </a>
        <hr class="dropdown-divider">
        <a href="#" class="dropdown-item text-center">See all message</a>
      </div>
    </div>
    <div class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
        <i class="fa fa-bell me-lg-2"></i>
        <span class="d-none d-lg-inline-flex">Notificatin</span>
      </a>
      <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
        <a href="#" class="dropdown-item">
          <h6 class="fw-normal mb-0">Profile updated</h6>
          <small>15 minutes ago</small>
        </a>
        <hr class="dropdown-divider">
        <a href="#" class="dropdown-item">
          <h6 class="fw-normal mb-0">New user added</h6>
          <small>15 minutes ago</small>
        </a>
        <hr class="dropdown-divider">
        <a href="#" class="dropdown-item">
          <h6 class="fw-normal mb-0">Password changed</h6>
          <small>15 minutes ago</small>
        </a>
        <hr class="dropdown-divider">
        <a href="#" class="dropdown-item text-center">See all notifications</a>
      </div>
    </div>
    <div class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
        <%= image_tag current_user.avatar, class: "rounded-circle", style: "width: 40px; height: 40px;" if current_user.avatar.attached? %>

        <span class="d-none d-lg-inline-flex"><%= current_user.full_name %></span>
      </a>
      <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
        <% if current_user %>
          <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
          <a href="#" class="dropdown-item">Settings</a>
          <%= link_to "Log Out", destroy_user_session_path, 'data-turbo-method': :delete, class: "dropdown-item"  %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<!-- Navbar End -->

app/views/shared/_menu.html.erb
<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
  <nav class="navbar bg-light navbar-light">
    <a href="index.html" class="navbar-brand mx-4 mb-3">
      <h3 class="text-primary color-text"><i class="fa fa-hashtag me-2"></i>LIGMATON</h3>
    </a>
    <div class="d-flex align-items-center ms-4 mb-4">
      <div class="position-relative">
        <%= image_tag admin.avatar, class: "rounded-circle", style: "width: 40px; height: 40px;" if admin %>
        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
      </div>
      <div class="ms-3">
<!--        <h6 class="mb-0"><%#= admin.full_name %></h6>-->
<!--        <span><%#= admin.role.capitalize %></span>-->
      </div>
    </div>
    <div class="navbar-nav w-100 p-3">
      <a href="index.html" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Elements</a>
        <div class="dropdown-menu bg-transparent border-0">
          <a href="button.html" class="dropdown-item">Buttons</a>
          <a href="typography.html" class="dropdown-item">Typography</a>
          <a href="element.html" class="dropdown-item">Other Elements</a>
        </div>
      </div>
      <%= link_to "#{fa_icon("th me-2")} #{I18n.t("users")}".html_safe, users_path, class: "nav-item nav-link" if can?(:crud, User) %>
      <%= link_to "#{fa_icon("table me-2")} #{I18n.t("departments")}".html_safe, departments_path, class: "nav-item nav-link" %>
      <%= link_to "#{fa_icon("keyboard me-2")} #{I18n.t("roles")}".html_safe, roles_path, class: "nav-item nav-link" %>
      <%= link_to "#{fa_icon("chart-bar  me-2")} #{I18n.t("permissions")}".html_safe, permissions_path, class: "nav-item nav-link" %>
      <%= link_to "#{fa_icon("car  me-2")} #{I18n.t("cars")}".html_safe, cars_path, class: "nav-item nav-link" %>
      <%= link_to "#{fa_icon("child  me-2")} #{I18n.t("partners")}".html_safe, partners_path, class: "nav-item nav-link" %>
      <%= link_to "#{fa_icon("plane  me-2")} #{I18n.t("product_types")}".html_safe, product_types_path, class: "nav-item nav-link" %>
      <%= link_to "#{fa_icon("truck  me-2")} #{I18n.t("order_logs")}".html_safe, order_logs_path, class: "nav-item nav-link" %>
      <%#= link_to "#{fa_icon("keyboard  me-2")} #{I18n.t("registers")}".html_safe, registers_car_inspections_path, class: "nav-item nav-link" %>

      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i><%=  I18n.t("registers") %></a>
        <div class="dropdown-menu bg-transparent border-0">
          <%= link_to "#{I18n.t("activerecord.attributes.registers.car_inspection")}".html_safe, registers_car_inspections_path, class: "dropdown-item", style: "width: 100px;
        background: #7cd4ae;
        word-wrap: break-word;
        word-break: break-all;" %>
<!--          <a href="button.html" class="dropdown-item">Buttons</a>-->
<!--          <a href="typography.html" class="dropdown-item">Typography</a>-->
<!--          <a href="element.html" class="dropdown-item">Other Elements</a>-->
        </div> 
      </div>

      <a href="widget.html" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Widgets</a>
      <a href="form.html" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Forms</a>
      <a href="table.html" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a>
      <a href="chart.html" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Charts</a>
      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Pages</a>
        <div class="dropdown-menu bg-transparent border-0">
          <a href="signin.html" class="dropdown-item">Sign In</a>
          <a href="signup.html" class="dropdown-item">Sign Up</a>
          <a href="404.html" class="dropdown-item">404 Error</a>
          <a href="blank.html" class="dropdown-item">Blank Page</a>
        </div>
      </div>
    </div>
  </nav>
</div>
<!-- Sidebar End -->

app/views/shared/_spinner.html.erb
<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
  <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>
<!-- Spinner End -->

app/views/shared/_versions.html.erb
<table class="table table-striped table-hover table-bordered">
  <thead>
  <tr>
    <th>#</th>
    <th>Created At</th>
    <th>Author whodunnit</th>
    <th>Author version_author</th>
    <th>Event</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% object.send(local_assigns[:versions] || :versions).each_with_index do |version, index| %>
    <tr class="<%= 'info' if index == 0 %>">
      <td></td>
      <td><%= version.created_at %></td>
      <td><%= link_to(version.user.full_name, user_path(version.whodunnit)) if version.whodunnit %></td>
      <td><%= version.event %></td>
      <td>
        <%#= render('shared/change_set', version: version) if version.changeset.present? %>
        <%#= set_version_link(set_version_path, version.id) if set_version_path.present? && version.event != 'create' %>
        <%#= render('shared/change_notes', version: version) if version.change_notes.present? %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>