config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: "registration"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :departments
  resources :users
  resources :roles
  resources :permissions
  resources :cars
  namespace :registers do
    resources :car_inspections, except: :show
  end

  resources :partners do
    collection { post :import }
  end
  resources :product_types
  resources :order_logs
  # Defines the root path route ("/")
  root "departments#index"
end

app/models/order_log.rb
class OrderLog < ApplicationRecord

  has_many :order_details, dependent: :destroy
  accepts_nested_attributes_for :order_details, allow_destroy: true

  validates :date, presence: true , uniqueness: { message: 'Дата должна присутствовать и уникальна' }
  # validates :order_details, presence: true
  validates_associated :order_details, presence: true
  validate :unique_partner_ids_in_order_details

  # enum indicator_type: {
  #   all_submissions: 0,
  #   accepted_submissions: 1,
  #   all_submission_resources: 2,
  #   accepted_submission_resources: 3,
  #   form_field_range_levels: 4
  # }


  TYPE_ORDERS = {
    disp: 1,
    imn_bad: 2,
    hol2_8: 3,
    bad2_8: 4,
    hol8_15: 5,
    a: 6,
    lrs: 7,
    pac: 8
  }

  def type_orders=(type_orders)
    self[:type_orders] = (type_orders).map {|t| TYPE_ORDERS[t]}
  end

  def type_orders
    TYPE_ORDERS.keys.select {|t| self[:type_orders].to_i & TYPE_ORDERS[t] != 0}
  end

  def has_type_orders?(type_order)
  self[:type_orders].to_i & TYPE_ORDERS[type_order] != 0
  end

  private

  def unique_partner_ids_in_order_details
    # 1. Получаем активные детали (не помеченные на удаление)
    active_details = order_details.reject(&:marked_for_destruction?)

    # 2. Если активных нет — валидация не нужна
    return if active_details.empty?

    # 3. Собираем partner_id активных записей
    partner_ids = active_details.map(&:partner_id).compact

    # 4. Проверяем уникальность
    if partner_ids.size != partner_ids.uniq.size
      # Находим дубликаты
      duplicates = partner_ids.group_by(&:itself)
                              .select { |k, v| v.size > 1 }
                              .keys
      errors.add(
        :order_details,
        "содержат дублирующиеся partner_id: #{duplicates.join(', ')}"
      )
    end
  end


end

app/controllers/order_logs_controller.rb
class OrderLogsController < ApplicationController
  load_and_authorize_resource

  def index
    @order_logs = OrderLog.all #.order(:name).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @order_logs }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order_log }
    end
  end

  def new
    @order_log = OrderLog.new
    @order_log.order_details.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order_log }
    end
  end

  def edit
  end

  def create
    @order_log = OrderLog.new(order_log_params)

    if @order_log.save
      redirect_to @order_log, notice: 'Заказ успешно создан.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /order_logs/1
  def update
    if @order_log.update(order_log_params)
      redirect_to @order_log, notice: 'Заказ успешно обновлён.'
    else
      render :edit, status: :unprocessable_entity
    end
  end


  # def create
  #   service = CreateOrderLogService.new(order_log_params)
  #   @order_log = service.call
  #
  #
  #   respond_to do |format|
  #     if @order_log
  #       format.html { redirect_to @order_log, notice: 'Permission was successfully created.' }
  #       format.json { render json: @order_log, status: :created, location: @order_log }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @order_log.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def update
  #   service = CreateOrderLogService.new(order_log_params)
  #   @order_log = service.call
  #
  #   respond_to do |format|
  #     if @order_log
  #       format.html { redirect_to @order_log, notice: 'Permission was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @order_log.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def destroy
    @order_log.destroy
    respond_to do |format|
      format.html { redirect_to order_logs_url }
      format.json { head :no_content }
    end
  end

  protected

  def order_log_params
    permitted_fields = [
      :date,
      order_details_attributes: [
        :id,
        :partner_id,
        :_destroy,
        {
          orders_attributes: [:number, :type_order_id,
                              :_destroy, data_list: {}]
        }
      ]
    ]

    params.require(:order_log).permit(permitted_fields)
  end
end

app/helpers/order_logs_helper.rb
module OrderLogsHelper
end

app/views/order_logs/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= custom_form_for(@order_log, bootstrap3_form_options(html_class: "agent-form")) do |form| %>

      <% if @order_log.errors.present? %>
        <div class="alert alert-danger">
          <% @order_log.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
        </div>
      <% end %>

      <%= form.date_field :date %>

      <h3>Заказы</h3>
      <div id="order_details">
        <%= form.fields_for :order_details do |detail_form| %>
          <%= render "order_detail_fields", f: detail_form %>
        <% end %>
      </div>

      <!--  <button type="button" id="add_order_detail">Добавить заказ</button>-->
      <%= link_to "➕ Добавить заказ", "#", id: "add_order_detail", class: "btn btn-success btn-block" %>
      <!-- Шаблон для одного поля детали заказа -->
      <%= content_tag :div, id: "new_order_detail_template", style: "display: none;" do %>
        <%= form.fields_for :order_details, OrderDetail.new, child_index: "NEW_RECORD" do |f| %>
          <%= render "order_detail_fields", f: f %>
        <% end %>
      <% end %>

      <div class="row">
        <div class="col-sm-offset-3 col-sm-3 p-3">
          <%= form.submit "Save", class: "btn btn-primary btn-block" %>
          <%= link_to("Cancel", order_logs_path, class: "btn btn-dark btn-block") %>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/order_logs/_order_detail_fields.html.erb
<div class="row p-1">
  <div class="order_detail">
    <%= f.collection_select :partner_id, Partner.all, :id, :name %>
    <% if f.object.persisted? %>
      <%= f.hidden_field :_destroy %>
      <%= link_to "Удалить", "#", class: "btn btn-danger btn-block remove_order_detail" %>
    <% else %>
      <%= link_to "Удалить", "#", class: "btn btn-danger btn-block remove_order_detail" %>
    <% end %>
  </div>
</div>

app/views/order_logs/edit.html.erb
<%= render partial: "form" %>

app/views/order_logs/index.html.erb
<h1><%= I18n.t("order_logs") %></h1>

<%= link_to "#{I18n.t("activerecord.attributes.order_log.new_order_log")}", new_order_log_path %>
<div>
  <div>
    <table class="table  table-striped">
      <thead>
      <tr>
        <th scope="col"><%= I18n.t("activerecord.attributes.order_log.name") %></th>
<!--        <th scope="col"><%#= I18n.t("activerecord.attributes.partner.email") %></th>-->
<!--        <th scope="col"><%#= I18n.t("activerecord.attributes.partner.address") %></th>-->
<!--        <th scope="col"><%#= I18n.t("activerecord.attributes.partner.phone_number") %></th>-->
      </tr>
      </thead>
      <tbody>
      <% if @order_logs %>
        <% @order_logs.each do |order_log| %>
          <tr>
            <td>
              <a href="<%= order_log_path(order_log) %>">
                <h5> <%= order_log.date %> </h5>
              </a>
            </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/order_logs/new.html.erb
<h1><%= I18n.t("activerecord.attributes.order_log.new_order_log")%></h1>
<%= render partial: "form" %>

app/views/order_logs/show.html.erb
<div>
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
<!--        <img src="..." class="img-fluid rounded-start" alt="...">-->
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= @order_log.date %></h5>
          <div class="mb15">
            <%= link_to("Edit", edit_order_log_path(@order_log), class: "btn btn-primary btn-block pv10 fw600 mb10") if can?(:update, @order_log)  %>
            <%= link_to("Destroy", order_log_path(@order_log), data: { turbo_method: :delete, turbo_confirm: "Удалить партнера?" }, class: "btn btn-danger btn-block") if can?(:destroy, @order_log) %>
            <%= link_to("All Product Type", order_logs_path, class: "btn btn-block btn-dark pv10 fw600 mb10")%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>